### PR TITLE
Colin Preston  

### PR DESCRIPTION
**Pull request by Colin-Preston**

### CODE REVIEW

**Comment by mixelpixel** [comment]
@Colin-Preston 👋 Hi Colin, could you put your name in the PR title?
screen shot 2018-04-12 at 5 02 31 pm

Makes it a lot easier for PMs to find your work 😄

**Comment by Colin-Preston** [comment]
Oh crap got it

**Comment by mixelpixel** [comment]
Great to see you using the git commit messages to make informationally meaningful notes!

Do you know how to make git commit message bodies? Are you in the #git channel in Slack? Check out this post: https://lambdaschoolstudents.slack.com/archives/C5Z8BMX6K/p1523565197000063

😺

**Comment by designerexpert** [comment]
## Bootstrap Part II

### Style and Expand the Form
- [x] Add an email input
- [x] Add a third radio button option called "island"
- [x] Wrap inputs and radio buttons in a `form-group`

### Build Utility Classes into the Site
- [x] Vertically center the navigation on the far right of its container
- [x] Use border radius utility to round corners on images `adventure.jpg` and `fun.jpg`
- [x] Use the sticky top utility on the container-fluid div
- [ ] Use the spacer utility (ex: mt-1) to give `top-margin` and/or `bottom-margin` to elements that are too close together

### Build JavaScript Components
- [x] Introduce a carousel somewhere on the site, showcasing the images in the `img` folder
- [x] (1/2) Add one of the following JS components: Collapse, Dropdowns, Modals, Tooltips, Scrollspy, Navbar
- [x] (2/2) Add another of the above JavaScript components
- [ ] Add a comment to your code to show where you added each JavaScript component

### Stretch Goals
- [ ] Add volidation to your form
- [ ] Make every form field required

## Good Habits
- [x] Pull Request title is your first and last name (add any notes in the comment field)
- [x] Code has been committed regularly
- [x] Commit comments are informative
- [ ] Code is organized in a logical way

## Comments:
* Totally digging the embedded video 👍 I think that for working solo on this one you tackled quite a bit, and had fun with it.
* Would have liked to see better spacing throughout the whole site, and some padding on the left.
* Remove all unnecessary spacing inside the code, use comments instead.

**Pull request closed without merging**
