### PR TITLE
Started working on BootstrapII

### PR DESCRIPTION
**Pull request by adfaris**
Will add more comment and more commits as soon as I am done working on one part.

### CODE REVIEW

**Comment by adfaris** [comment]
Completed task one, which is adding an email input, adding a 3rd option in the radio buttons and naming it island and the last one styling it in a form group.

**Comment by adfaris** [comment]
Completed adding utility class to the cite, used flex utility to center and move the navigation to the right of the container, used border radius to round the corners of the images named adventure and fun, but I applied to all three pics, put sticky top on the header fluid container and at last used spacer mt and mb to make the cite more appealing to look at.

**Comment by adfaris** [comment]
Added a javascript component to the site. I have added comment on the index.html file.

**Comment by adfaris** [comment]
Added Navbar and Modal to the site, the modal is at the bottom of the site and replaced the varbar with bootstap navbar.

**Comment by adfaris** [comment]
Made the modal button block and large and changed the text to, "Click on me I am a modal"

**Comment by AndjDavis** [comment]
Hey hey, Bootstrap II is looking pretty good.  Just a couple of things.  Looks like you wrote position-sticky on your 'container-fluid', it should read 'sticky-top'.   Nice hamburger menu on smaller screens, that looks really nice on the page.   One thing of minor note would be to capitalize email on line 208 on the label.  Overall, looks very good.  Good job!

**Pull request closed without merging**
